fix: only load driver that used in config
```
raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```
This happen after 4679cf922832fe577a7b395ebe59664fd290a598
whatsapp will throw error when it cannot find libmagic

https://github.com/krypton-byte/neonize/blob/aeaa4d6deb3ded72eb8f6dad1ace7735a26e1207/docs/getting-started/installation.md#L108-L115

This seems a low level dependencies, most of time user don't need to
explicitly install it but can still throw error on nixos.