fix: only load driver that used in config (#9)
* delete claude settings

* whatsapp (untested)

* fix type error in telegram driver

* format

* fix discord doesnt work error

* fix napcat proxy

* wait i forgot to format

* Bump pyasn1 from 0.6.2 to 0.6.3 (#7)

Bumps [pyasn1](https://github.com/pyasn1/pyasn1) from 0.6.2 to 0.6.3.
- [Release notes](https://github.com/pyasn1/pyasn1/releases)
- [Changelog](https://github.com/pyasn1/pyasn1/blob/main/CHANGES.rst)
- [Commits](https://github.com/pyasn1/pyasn1/compare/v0.6.2...v0.6.3)

---
updated-dependencies:
- dependency-name: pyasn1
  dependency-version: 0.6.3
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix: only load driver that used in config

```
raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```
This happen after 4679cf922832fe577a7b395ebe59664fd290a598
whatsapp will throw error when it cannot find libmagic

https://github.com/krypton-byte/neonize/blob/aeaa4d6deb3ded72eb8f6dad1ace7735a26e1207/docs/getting-started/installation.md#L108-L115

This seems a low level dependencies, most of time user don't need to
explicitly install it but can still throw error on nixos.

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: ntkrnl64 <nt@krnl64.win>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: wyf9 <wyf9@siiway.org>