v0.2 (#12)
* support setting `proxy = null` to disable proxy
- fix missing docs part for several drivers

* webhook & slack proxy support

* about logging
- set default python version & project version

* fixes
- proxy: str -> proxy: str | None
- add some default config for out-of-box usage
- log optimize [undone]
- discord webhook fix [undone: cannot receive message]

* Squashed commit of the following:

commit b916ef4fc3c2e3f5f3c75e56077632597fe23b42
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 23:44:36 2026 +0800

    wait i forgot to format

commit 253e72b7ee850d35a6755ea4da312fc5d6d06ee0
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 23:43:39 2026 +0800

    fix napcat proxy

commit dfde18f9aa52749c1b14664e002d0a4ff4c3b8fc
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 23:43:05 2026 +0800

    fix discord doesnt work error

commit 77447ee7a6c7c13cdeceb580882ed08d66e143d6
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 23:08:31 2026 +0800

    format

commit 121bc0860441f4f8757db46dea48d545388bda45
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 18:48:44 2026 +0800

    fix type error in telegram driver

commit 4679cf922832fe577a7b395ebe59664fd290a598
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 18:48:15 2026 +0800

    whatsapp (untested)

commit 893acaa6e0c96132c0ed83801f38ae5fb667cc3d
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 18:35:02 2026 +0800

    delete claude settings

* add matrix e2e encryption support

* update docs for matrix

* use dev branch pls...
Squashed commit of the following:

commit 71cfe0aa75c7e15f89337634c4ab6acbfa0b364e
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Wed Mar 18 06:52:53 2026 +0800

    Bump pyasn1 from 0.6.2 to 0.6.3 (#7)

    Bumps [pyasn1](https://github.com/pyasn1/pyasn1) from 0.6.2 to 0.6.3.
    - [Release notes](https://github.com/pyasn1/pyasn1/releases)
    - [Changelog](https://github.com/pyasn1/pyasn1/blob/main/CHANGES.rst)
    - [Commits](https://github.com/pyasn1/pyasn1/compare/v0.6.2...v0.6.3)

    ---
    updated-dependencies:
    - dependency-name: pyasn1
      dependency-version: 0.6.3
      dependency-type: indirect
    ...

    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

commit b916ef4fc3c2e3f5f3c75e56077632597fe23b42
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 23:44:36 2026 +0800

    wait i forgot to format

commit 253e72b7ee850d35a6755ea4da312fc5d6d06ee0
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 23:43:39 2026 +0800

    fix napcat proxy

commit dfde18f9aa52749c1b14664e002d0a4ff4c3b8fc
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 23:43:05 2026 +0800

    fix discord doesnt work error

commit 77447ee7a6c7c13cdeceb580882ed08d66e143d6
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 23:08:31 2026 +0800

    format

commit 121bc0860441f4f8757db46dea48d545388bda45
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 18:48:44 2026 +0800

    fix type error in telegram driver

commit 4679cf922832fe577a7b395ebe59664fd290a598
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 18:48:15 2026 +0800

    whatsapp (untested)

commit 893acaa6e0c96132c0ed83801f38ae5fb667cc3d
Author: ntkrnl64 <nt@krnl64.win>
Date:   Sun Mar 15 18:35:02 2026 +0800

    delete claude settings

* fix: only load driver that used in config (#9)

* delete claude settings

* whatsapp (untested)

* fix type error in telegram driver

* format

* fix discord doesnt work error

* fix napcat proxy

* wait i forgot to format

* Bump pyasn1 from 0.6.2 to 0.6.3 (#7)

Bumps [pyasn1](https://github.com/pyasn1/pyasn1) from 0.6.2 to 0.6.3.
- [Release notes](https://github.com/pyasn1/pyasn1/releases)
- [Changelog](https://github.com/pyasn1/pyasn1/blob/main/CHANGES.rst)
- [Commits](https://github.com/pyasn1/pyasn1/compare/v0.6.2...v0.6.3)

---
updated-dependencies:
- dependency-name: pyasn1
  dependency-version: 0.6.3
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix: only load driver that used in config

```
raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```
This happen after 4679cf922832fe577a7b395ebe59664fd290a598
whatsapp will throw error when it cannot find libmagic

https://github.com/krypton-byte/neonize/blob/aeaa4d6deb3ded72eb8f6dad1ace7735a26e1207/docs/getting-started/installation.md#L108-L115

This seems a low level dependencies, most of time user don't need to
explicitly install it but can still throw error on nixos.

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: ntkrnl64 <nt@krnl64.win>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: wyf9 <wyf9@siiway.org>

* use vodozemac for matrix driver instead of deprecated python-olm

* update whatsapp doc for sys reqs

* source proxy passthrough for attachment downloading
- fix discord webhook sending

* some todos
- fix startup version display

* doc updates
- add icon
- feature links & facts upd
- readme todos
- ...

* add ruff workflow
- better logging level showing

* fix workflow

* tg avatar proxy support
- enhanced debug logging
- move todos to glint

* better richheader page
- ruff ignore: E741

* upd ruff.yml
- add missing x-robots-tag header to workers

* [skip ci] style: code auto-fix & format

* feishu set ws to default method
- upd deps

* fix: stop process will be breaked by driver exception when sending messages
- feishu: docs get chat id + log
- characters replacement (?)
- less logs

* [skip ci] style: code auto-fix & format

* add optional id to rule config

* cross-platform reply fix

* [skip ci] style: code auto-fix & format

* dc bot send fallback format fix
- upd docs (pub proxy hosts as default)

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Rhen Cloud <i@rhen.cloud>
Co-authored-by: phanium <91544758+phanen@users.noreply.github.com>
Co-authored-by: ntkrnl64 <nt@krnl64.win>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>